<?php
/**
 * ShipmentResponseItemsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\AusPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Australia Post Shipping & Tracking API
 *
 * Integrating your systems with Australia Post and StarTrack using the Shipping and Tracking APIs enables you to lodge the information we need when sending parcels through our delivery networks.  You can currently use the Shipping and Tracking APIs for...  - Lodgement of parcels – creates an order, including all the shipments and items, and lodges the parcels with Australia Post and StarTrack  - Label printing - prints our most up-to-date labels to improve your operational efficiency  - Getting your contract details - gives all your current account information, including products, contract expiry dates & product features  - Getting your contract pricing - provides an indicative price at checkout to enable the best service to be selected, giving you confidence of cost of lodgement  - Tracking your parcels - allows you to easily surface tracking information on your website for your staff or customers
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cwhemmings@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Please update the test case below to test the model.
 */

namespace ChrisHemmings\AusPost;

/**
 * ShipmentResponseItemsTest Class Doc Comment
 *
 * @category    Class
 * @description ShipmentResponseItems
 * @package     ChrisHemmings\AusPost
 * @author      Swagger Codegen team
 * @link        https://github.com/swagger-api/swagger-codegen
 */
class ShipmentResponseItemsTest extends \PHPUnit_Framework_TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "ShipmentResponseItems"
     */
    public function testShipmentResponseItems()
    {
    }

    /**
     * Test attribute "weight"
     */
    public function testPropertyWeight()
    {
    }

    /**
     * Test attribute "authority_to_leave"
     */
    public function testPropertyAuthorityToLeave()
    {
    }

    /**
     * Test attribute "safe_drop_enabled"
     */
    public function testPropertySafeDropEnabled()
    {
    }

    /**
     * Test attribute "allow_partial_delivery"
     */
    public function testPropertyAllowPartialDelivery()
    {
    }

    /**
     * Test attribute "item_id"
     */
    public function testPropertyItemId()
    {
    }

    /**
     * Test attribute "item_reference"
     */
    public function testPropertyItemReference()
    {
    }

    /**
     * Test attribute "tracking_details"
     */
    public function testPropertyTrackingDetails()
    {
    }

    /**
     * Test attribute "product_id"
     */
    public function testPropertyProductId()
    {
    }

    /**
     * Test attribute "itemsummary"
     */
    public function testPropertyItemsummary()
    {
    }

    /**
     * Test attribute "item_contents"
     */
    public function testPropertyItemContents()
    {
    }

    /**
     * Test attribute "options"
     */
    public function testPropertyOptions()
    {
    }

    /**
     * Test attribute "shipment_summary"
     */
    public function testPropertyShipmentSummary()
    {
    }

    /**
     * Test attribute "movement_type"
     */
    public function testPropertyMovementType()
    {
    }

    /**
     * Test attribute "charge_to_account"
     */
    public function testPropertyChargeToAccount()
    {
    }
}
