<?php
/**
 * ShipmentItem
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\AusPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Australia Post Shipping & Tracking API
 *
 * Integrating your systems with Australia Post and StarTrack using the Shipping and Tracking APIs enables you to lodge the information we need when sending parcels through our delivery networks.  You can currently use the Shipping and Tracking APIs for...  - Lodgement of parcels – creates an order, including all the shipments and items, and lodges the parcels with Australia Post and StarTrack  - Label printing - prints our most up-to-date labels to improve your operational efficiency  - Getting your contract details - gives all your current account information, including products, contract expiry dates & product features  - Getting your contract pricing - provides an indicative price at checkout to enable the best service to be selected, giving you confidence of cost of lodgement  - Tracking your parcels - allows you to easily surface tracking information on your website for your staff or customers
 *
 * OpenAPI spec version: 1.0.2
 * Contact: cwhemmings@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 3.0.52
 */
/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ChrisHemmings\AusPost\Client\Model;

use \ArrayAccess;
use \ChrisHemmings\AusPost\ObjectSerializer;

/**
 * ShipmentItem Class Doc Comment
 *
 * @category Class
 * @package  ChrisHemmings\AusPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipmentItem implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ShipmentItem';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'classification_type' => 'string',
        'description_of_other' => 'string',
        'commercial_value' => 'bool',
        'item_reference' => 'string',
        'product_id' => 'string',
        'length' => 'string',
        'height' => 'string',
        'width' => 'string',
        'weight' => 'string',
        'authority_to_leave' => 'bool',
        'allow_partial_delivery' => 'bool',
        'features' => '\ChrisHemmings\AusPost\Client\Model\ItemFeatures',
        'item_contents' => '\ChrisHemmings\AusPost\Client\Model\ItemContents[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'classification_type' => null,
        'description_of_other' => null,
        'commercial_value' => null,
        'item_reference' => null,
        'product_id' => null,
        'length' => null,
        'height' => null,
        'width' => null,
        'weight' => null,
        'authority_to_leave' => null,
        'allow_partial_delivery' => null,
        'features' => null,
        'item_contents' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'classification_type' => 'classification_type',
        'description_of_other' => 'description_of_other',
        'commercial_value' => 'commercial_value',
        'item_reference' => 'item_reference',
        'product_id' => 'product_id',
        'length' => 'length',
        'height' => 'height',
        'width' => 'width',
        'weight' => 'weight',
        'authority_to_leave' => 'authority_to_leave',
        'allow_partial_delivery' => 'allow_partial_delivery',
        'features' => 'features',
        'item_contents' => 'item_contents'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'classification_type' => 'setClassificationType',
        'description_of_other' => 'setDescriptionOfOther',
        'commercial_value' => 'setCommercialValue',
        'item_reference' => 'setItemReference',
        'product_id' => 'setProductId',
        'length' => 'setLength',
        'height' => 'setHeight',
        'width' => 'setWidth',
        'weight' => 'setWeight',
        'authority_to_leave' => 'setAuthorityToLeave',
        'allow_partial_delivery' => 'setAllowPartialDelivery',
        'features' => 'setFeatures',
        'item_contents' => 'setItemContents'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'classification_type' => 'getClassificationType',
        'description_of_other' => 'getDescriptionOfOther',
        'commercial_value' => 'getCommercialValue',
        'item_reference' => 'getItemReference',
        'product_id' => 'getProductId',
        'length' => 'getLength',
        'height' => 'getHeight',
        'width' => 'getWidth',
        'weight' => 'getWeight',
        'authority_to_leave' => 'getAuthorityToLeave',
        'allow_partial_delivery' => 'getAllowPartialDelivery',
        'features' => 'getFeatures',
        'item_contents' => 'getItemContents'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }



    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['classification_type'] = isset($data['classification_type']) ? $data['classification_type'] : null;
        $this->container['description_of_other'] = isset($data['description_of_other']) ? $data['description_of_other'] : null;
        $this->container['commercial_value'] = isset($data['commercial_value']) ? $data['commercial_value'] : null;
        $this->container['item_reference'] = isset($data['item_reference']) ? $data['item_reference'] : null;
        $this->container['product_id'] = isset($data['product_id']) ? $data['product_id'] : null;
        $this->container['length'] = isset($data['length']) ? $data['length'] : null;
        $this->container['height'] = isset($data['height']) ? $data['height'] : null;
        $this->container['width'] = isset($data['width']) ? $data['width'] : null;
        $this->container['weight'] = isset($data['weight']) ? $data['weight'] : null;
        $this->container['authority_to_leave'] = isset($data['authority_to_leave']) ? $data['authority_to_leave'] : null;
        $this->container['allow_partial_delivery'] = isset($data['allow_partial_delivery']) ? $data['allow_partial_delivery'] : null;
        $this->container['features'] = isset($data['features']) ? $data['features'] : null;
        $this->container['item_contents'] = isset($data['item_contents']) ? $data['item_contents'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets classification_type
     *
     * @return string
     */
    public function getClassificationType()
    {
        return $this->container['classification_type'];
    }

    /**
     * Sets classification_type
     *
     * @param string $classification_type classification_type
     *
     * @return $this
     */
    public function setClassificationType($classification_type)
    {
        $this->container['classification_type'] = $classification_type;

        return $this;
    }

    /**
     * Gets description_of_other
     *
     * @return string
     */
    public function getDescriptionOfOther()
    {
        return $this->container['description_of_other'];
    }

    /**
     * Sets description_of_other
     *
     * @param string $description_of_other description_of_other
     *
     * @return $this
     */
    public function setDescriptionOfOther($description_of_other)
    {
        $this->container['description_of_other'] = $description_of_other;

        return $this;
    }

    /**
     * Gets commercial_value
     *
     * @return bool
     */
    public function getCommercialValue()
    {
        return $this->container['commercial_value'];
    }

    /**
     * Sets commercial_value
     *
     * @param bool $commercial_value commercial_value
     *
     * @return $this
     */
    public function setCommercialValue($commercial_value)
    {
        $this->container['commercial_value'] = $commercial_value;

        return $this;
    }

    /**
     * Gets item_reference
     *
     * @return string
     */
    public function getItemReference()
    {
        return $this->container['item_reference'];
    }

    /**
     * Sets item_reference
     *
     * @param string $item_reference item_reference
     *
     * @return $this
     */
    public function setItemReference($item_reference)
    {
        $this->container['item_reference'] = $item_reference;

        return $this;
    }

    /**
     * Gets product_id
     *
     * @return string
     */
    public function getProductId()
    {
        return $this->container['product_id'];
    }

    /**
     * Sets product_id
     *
     * @param string $product_id product_id
     *
     * @return $this
     */
    public function setProductId($product_id)
    {
        $this->container['product_id'] = $product_id;

        return $this;
    }

    /**
     * Gets length
     *
     * @return string
     */
    public function getLength()
    {
        return $this->container['length'];
    }

    /**
     * Sets length
     *
     * @param string $length length
     *
     * @return $this
     */
    public function setLength($length)
    {
        $this->container['length'] = $length;

        return $this;
    }

    /**
     * Gets height
     *
     * @return string
     */
    public function getHeight()
    {
        return $this->container['height'];
    }

    /**
     * Sets height
     *
     * @param string $height height
     *
     * @return $this
     */
    public function setHeight($height)
    {
        $this->container['height'] = $height;

        return $this;
    }

    /**
     * Gets width
     *
     * @return string
     */
    public function getWidth()
    {
        return $this->container['width'];
    }

    /**
     * Sets width
     *
     * @param string $width width
     *
     * @return $this
     */
    public function setWidth($width)
    {
        $this->container['width'] = $width;

        return $this;
    }

    /**
     * Gets weight
     *
     * @return string
     */
    public function getWeight()
    {
        return $this->container['weight'];
    }

    /**
     * Sets weight
     *
     * @param string $weight weight
     *
     * @return $this
     */
    public function setWeight($weight)
    {
        $this->container['weight'] = $weight;

        return $this;
    }

    /**
     * Gets authority_to_leave
     *
     * @return bool
     */
    public function getAuthorityToLeave()
    {
        return $this->container['authority_to_leave'];
    }

    /**
     * Sets authority_to_leave
     *
     * @param bool $authority_to_leave authority_to_leave
     *
     * @return $this
     */
    public function setAuthorityToLeave($authority_to_leave)
    {
        $this->container['authority_to_leave'] = $authority_to_leave;

        return $this;
    }

    /**
     * Gets allow_partial_delivery
     *
     * @return bool
     */
    public function getAllowPartialDelivery()
    {
        return $this->container['allow_partial_delivery'];
    }

    /**
     * Sets allow_partial_delivery
     *
     * @param bool $allow_partial_delivery allow_partial_delivery
     *
     * @return $this
     */
    public function setAllowPartialDelivery($allow_partial_delivery)
    {
        $this->container['allow_partial_delivery'] = $allow_partial_delivery;

        return $this;
    }

    /**
     * Gets features
     *
     * @return \ChrisHemmings\AusPost\Client\Model\ItemFeatures
     */
    public function getFeatures()
    {
        return $this->container['features'];
    }

    /**
     * Sets features
     *
     * @param \ChrisHemmings\AusPost\Client\Model\ItemFeatures $features features
     *
     * @return $this
     */
    public function setFeatures($features)
    {
        $this->container['features'] = $features;

        return $this;
    }

    /**
     * Gets item_contents
     *
     * @return \ChrisHemmings\AusPost\Client\Model\ItemContents[]
     */
    public function getItemContents()
    {
        return $this->container['item_contents'];
    }

    /**
     * Sets item_contents
     *
     * @param \ChrisHemmings\AusPost\Client\Model\ItemContents[] $item_contents item_contents
     *
     * @return $this
     */
    public function setItemContents($item_contents)
    {
        $this->container['item_contents'] = $item_contents;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    #[\ReturnTypeWillChange]
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    #[\ReturnTypeWillChange]
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    #[\ReturnTypeWillChange]
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}
