<?php
/**
 * ShipmentRequest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChrisHemmings\AusPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */

/**
 * Australia Post Shipping & Tracking API
 *
 * Integrating your systems with Australia Post and StarTrack using the Shipping and Tracking APIs enables you to lodge the information we need when sending parcels through our delivery networks.  You can currently use the Shipping and Tracking APIs for...  - Lodgement of parcels – creates an order, including all the shipments and items, and lodges the parcels with Australia Post and StarTrack  - Label printing - prints our most up-to-date labels to improve your operational efficiency  - Getting your contract details - gives all your current account information, including products, contract expiry dates & product features  - Getting your contract pricing - provides an indicative price at checkout to enable the best service to be selected, giving you confidence of cost of lodgement  - Tracking your parcels - allows you to easily surface tracking information on your website for your staff or customers
 *
 * OpenAPI spec version: 1.0.0
 * Contact: cwhemmings@gmail.com
 * Generated by: https://github.com/swagger-api/swagger-codegen.git
 * Swagger Codegen version: 2.4.19
 */

/**
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen
 * Do not edit the class manually.
 */

namespace ChrisHemmings\AusPost\Client\Model;

use \ArrayAccess;
use \ChrisHemmings\AusPost\ObjectSerializer;

/**
 * ShipmentRequest Class Doc Comment
 *
 * @category Class
 * @package  ChrisHemmings\AusPost
 * @author   Swagger Codegen team
 * @link     https://github.com/swagger-api/swagger-codegen
 */
class ShipmentRequest implements ModelInterface, ArrayAccess
{
    const DISCRIMINATOR = null;

    /**
      * The original name of the model.
      *
      * @var string
      */
    protected static $swaggerModelName = 'ShipmentRequest';

    /**
      * Array of property to type mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerTypes = [
        'shipment_reference' => 'string',
        'customer_reference_1' => 'string',
        'customer_reference_2' => 'string',
        'email_tracking_enabled' => 'bool',
        'from' => '\ChrisHemmings\AusPost\Client\Model\ShipmentFromAddress',
        'to' => '\ChrisHemmings\AusPost\Client\Model\ShipmentToAddress',
        'items' => '\ChrisHemmings\AusPost\Client\Model\ShipmentItem[]'
    ];

    /**
      * Array of property to format mappings. Used for (de)serialization
      *
      * @var string[]
      */
    protected static $swaggerFormats = [
        'shipment_reference' => null,
        'customer_reference_1' => null,
        'customer_reference_2' => null,
        'email_tracking_enabled' => null,
        'from' => null,
        'to' => null,
        'items' => null
    ];

    /**
     * Array of property to type mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerTypes()
    {
        return self::$swaggerTypes;
    }

    /**
     * Array of property to format mappings. Used for (de)serialization
     *
     * @return array
     */
    public static function swaggerFormats()
    {
        return self::$swaggerFormats;
    }

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @var string[]
     */
    protected static $attributeMap = [
        'shipment_reference' => 'shipment_reference',
        'customer_reference_1' => 'customer_reference_1',
        'customer_reference_2' => 'customer_reference_2',
        'email_tracking_enabled' => 'email_tracking_enabled',
        'from' => 'from',
        'to' => 'to',
        'items' => 'items'
    ];

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @var string[]
     */
    protected static $setters = [
        'shipment_reference' => 'setShipmentReference',
        'customer_reference_1' => 'setCustomerReference1',
        'customer_reference_2' => 'setCustomerReference2',
        'email_tracking_enabled' => 'setEmailTrackingEnabled',
        'from' => 'setFrom',
        'to' => 'setTo',
        'items' => 'setItems'
    ];

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @var string[]
     */
    protected static $getters = [
        'shipment_reference' => 'getShipmentReference',
        'customer_reference_1' => 'getCustomerReference1',
        'customer_reference_2' => 'getCustomerReference2',
        'email_tracking_enabled' => 'getEmailTrackingEnabled',
        'from' => 'getFrom',
        'to' => 'getTo',
        'items' => 'getItems'
    ];

    /**
     * Array of attributes where the key is the local name,
     * and the value is the original name
     *
     * @return array
     */
    public static function attributeMap()
    {
        return self::$attributeMap;
    }

    /**
     * Array of attributes to setter functions (for deserialization of responses)
     *
     * @return array
     */
    public static function setters()
    {
        return self::$setters;
    }

    /**
     * Array of attributes to getter functions (for serialization of requests)
     *
     * @return array
     */
    public static function getters()
    {
        return self::$getters;
    }

    /**
     * The original name of the model.
     *
     * @return string
     */
    public function getModelName()
    {
        return self::$swaggerModelName;
    }

    

    

    /**
     * Associative array for storing property values
     *
     * @var mixed[]
     */
    protected $container = [];

    /**
     * Constructor
     *
     * @param mixed[] $data Associated array of property values
     *                      initializing the model
     */
    public function __construct(array $data = null)
    {
        $this->container['shipment_reference'] = isset($data['shipment_reference']) ? $data['shipment_reference'] : null;
        $this->container['customer_reference_1'] = isset($data['customer_reference_1']) ? $data['customer_reference_1'] : null;
        $this->container['customer_reference_2'] = isset($data['customer_reference_2']) ? $data['customer_reference_2'] : null;
        $this->container['email_tracking_enabled'] = isset($data['email_tracking_enabled']) ? $data['email_tracking_enabled'] : null;
        $this->container['from'] = isset($data['from']) ? $data['from'] : null;
        $this->container['to'] = isset($data['to']) ? $data['to'] : null;
        $this->container['items'] = isset($data['items']) ? $data['items'] : null;
    }

    /**
     * Show all the invalid properties with reasons.
     *
     * @return array invalid properties with reasons
     */
    public function listInvalidProperties()
    {
        $invalidProperties = [];

        if (!is_null($this->container['customer_reference_1']) && (mb_strlen($this->container['customer_reference_1']) > 50)) {
            $invalidProperties[] = "invalid value for 'customer_reference_1', the character length must be smaller than or equal to 50.";
        }

        if (!is_null($this->container['customer_reference_2']) && (mb_strlen($this->container['customer_reference_2']) > 50)) {
            $invalidProperties[] = "invalid value for 'customer_reference_2', the character length must be smaller than or equal to 50.";
        }

        return $invalidProperties;
    }

    /**
     * Validate all the properties in the model
     * return true if all passed
     *
     * @return bool True if all properties are valid
     */
    public function valid()
    {
        return count($this->listInvalidProperties()) === 0;
    }


    /**
     * Gets shipment_reference
     *
     * @return string
     */
    public function getShipmentReference()
    {
        return $this->container['shipment_reference'];
    }

    /**
     * Sets shipment_reference
     *
     * @param string $shipment_reference shipment_reference
     *
     * @return $this
     */
    public function setShipmentReference($shipment_reference)
    {
        $this->container['shipment_reference'] = $shipment_reference;

        return $this;
    }

    /**
     * Gets customer_reference_1
     *
     * @return string
     */
    public function getCustomerReference1()
    {
        return $this->container['customer_reference_1'];
    }

    /**
     * Sets customer_reference_1
     *
     * @param string $customer_reference_1 customer_reference_1
     *
     * @return $this
     */
    public function setCustomerReference1($customer_reference_1)
    {
        if (!is_null($customer_reference_1) && (mb_strlen($customer_reference_1) > 50)) {
            throw new \InvalidArgumentException('invalid length for $customer_reference_1 when calling ShipmentRequest., must be smaller than or equal to 50.');
        }

        $this->container['customer_reference_1'] = $customer_reference_1;

        return $this;
    }

    /**
     * Gets customer_reference_2
     *
     * @return string
     */
    public function getCustomerReference2()
    {
        return $this->container['customer_reference_2'];
    }

    /**
     * Sets customer_reference_2
     *
     * @param string $customer_reference_2 customer_reference_2
     *
     * @return $this
     */
    public function setCustomerReference2($customer_reference_2)
    {
        if (!is_null($customer_reference_2) && (mb_strlen($customer_reference_2) > 50)) {
            throw new \InvalidArgumentException('invalid length for $customer_reference_2 when calling ShipmentRequest., must be smaller than or equal to 50.');
        }

        $this->container['customer_reference_2'] = $customer_reference_2;

        return $this;
    }

    /**
     * Gets email_tracking_enabled
     *
     * @return bool
     */
    public function getEmailTrackingEnabled()
    {
        return $this->container['email_tracking_enabled'];
    }

    /**
     * Sets email_tracking_enabled
     *
     * @param bool $email_tracking_enabled email_tracking_enabled
     *
     * @return $this
     */
    public function setEmailTrackingEnabled($email_tracking_enabled)
    {
        $this->container['email_tracking_enabled'] = $email_tracking_enabled;

        return $this;
    }

    /**
     * Gets from
     *
     * @return \ChrisHemmings\AusPost\Client\Model\ShipmentFromAddress
     */
    public function getFrom()
    {
        return $this->container['from'];
    }

    /**
     * Sets from
     *
     * @param \ChrisHemmings\AusPost\Client\Model\ShipmentFromAddress $from from
     *
     * @return $this
     */
    public function setFrom($from)
    {
        $this->container['from'] = $from;

        return $this;
    }

    /**
     * Gets to
     *
     * @return \ChrisHemmings\AusPost\Client\Model\ShipmentToAddress
     */
    public function getTo()
    {
        return $this->container['to'];
    }

    /**
     * Sets to
     *
     * @param \ChrisHemmings\AusPost\Client\Model\ShipmentToAddress $to to
     *
     * @return $this
     */
    public function setTo($to)
    {
        $this->container['to'] = $to;

        return $this;
    }

    /**
     * Gets items
     *
     * @return \ChrisHemmings\AusPost\Client\Model\ShipmentItem[]
     */
    public function getItems()
    {
        return $this->container['items'];
    }

    /**
     * Sets items
     *
     * @param \ChrisHemmings\AusPost\Client\Model\ShipmentItem[] $items items
     *
     * @return $this
     */
    public function setItems($items)
    {
        $this->container['items'] = $items;

        return $this;
    }
    /**
     * Returns true if offset exists. False otherwise.
     *
     * @param integer $offset Offset
     *
     * @return boolean
     */
    public function offsetExists($offset)
    {
        return isset($this->container[$offset]);
    }

    /**
     * Gets offset.
     *
     * @param integer $offset Offset
     *
     * @return mixed
     */
    public function offsetGet($offset)
    {
        return isset($this->container[$offset]) ? $this->container[$offset] : null;
    }

    /**
     * Sets value based on offset.
     *
     * @param integer $offset Offset
     * @param mixed   $value  Value to be set
     *
     * @return void
     */
    public function offsetSet($offset, $value)
    {
        if (is_null($offset)) {
            $this->container[] = $value;
        } else {
            $this->container[$offset] = $value;
        }
    }

    /**
     * Unsets offset.
     *
     * @param integer $offset Offset
     *
     * @return void
     */
    public function offsetUnset($offset)
    {
        unset($this->container[$offset]);
    }

    /**
     * Gets the string presentation of the object
     *
     * @return string
     */
    public function __toString()
    {
        if (defined('JSON_PRETTY_PRINT')) { // use JSON pretty print
            return json_encode(
                ObjectSerializer::sanitizeForSerialization($this),
                JSON_PRETTY_PRINT
            );
        }

        return json_encode(ObjectSerializer::sanitizeForSerialization($this));
    }
}


